"""initial schema

Revision ID: 61ba8c4b73f2
Revises: 
Create Date: 2026-02-22 15:15:20.470195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ba8c4b73f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('context', sa.String(length=100), nullable=True),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('qudurat_students', sa.Integer(), nullable=True),
    sa.Column('tahsili_students', sa.Integer(), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('preferred_duration', sa.String(length=20), nullable=True),
    sa.Column('estimated_band', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('estimated_student_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], name='fk_orgs_created_by_admin_id_users', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('stripe_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stripe_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stripe_events_stripe_event_id'), ['stripe_event_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'SCHOOL_LEADER', 'DRFAHM_ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('app_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('exam', sa.String(length=20), nullable=True),
    sa.Column('plan_id', sa.String(length=20), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_events_user_id'), ['user_id'], unique=False)

    op.create_table('entitlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('exam', sa.String(length=20), nullable=False),
    sa.Column('plan_id', sa.Enum('FREE', 'BASIC', 'PREMIUM', name='planid'), nullable=False),
    sa.Column('plan_type', sa.Enum('INDIVIDUAL_BASIC_3M', 'INDIVIDUAL_PREMIUM_1Y', 'SCHOOL_PREMIUM_1Y', name='plantype'), nullable=False),
    sa.Column('max_world_index', sa.Integer(), nullable=False),
    sa.Column('entitlement_starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entitlement_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_session_id')
    )
    with op.batch_alter_table('entitlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entitlements_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entitlements_user_id'), ['user_id'], unique=False)

    op.create_table('exam_trials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam', sa.String(length=20), nullable=False),
    sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trial_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exam', name='uq_exam_trial_user_exam')
    )
    with op.batch_alter_table('exam_trials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_trials_user_id'), ['user_id'], unique=False)

    op.create_table('level_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam', sa.String(length=20), nullable=False),
    sa.Column('world_key', sa.String(length=30), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exam', 'world_key', 'level_number', name='uq_level_progress_user_exam_world_level')
    )
    with op.batch_alter_table('level_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_level_progress_user_id'), ['user_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam', sa.String(length=20), nullable=False),
    sa.Column('world_key', sa.String(length=30), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.Column('option_c', sa.Text(), nullable=False),
    sa.Column('option_d', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('currently_editing_admin_id', sa.Integer(), nullable=True),
    sa.Column('editing_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['currently_editing_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_reviewed_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam', 'world_key', 'index', name='uq_question_exam_world_index')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_exam'), ['exam'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_world_key'), ['world_key'], unique=False)

    op.create_table('world_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam', sa.String(length=20), nullable=False),
    sa.Column('world_key', sa.String(length=30), nullable=False),
    sa.Column('fully_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exam', 'world_key', name='uq_world_progress_user_exam_world')
    )
    with op.batch_alter_table('world_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_progress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_progress_user_id'))

    op.drop_table('world_progress')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_world_key'))
        batch_op.drop_index(batch_op.f('ix_questions_exam'))

    op.drop_table('questions')
    with op.batch_alter_table('level_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_level_progress_user_id'))

    op.drop_table('level_progress')
    with op.batch_alter_table('exam_trials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_trials_user_id'))

    op.drop_table('exam_trials')
    with op.batch_alter_table('entitlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entitlements_user_id'))
        batch_op.drop_index(batch_op.f('ix_entitlements_org_id'))

    op.drop_table('entitlements')
    with op.batch_alter_table('app_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_events_user_id'))

    op.drop_table('app_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_org_id'))

    op.drop_table('users')
    with op.batch_alter_table('stripe_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stripe_events_stripe_event_id'))

    op.drop_table('stripe_events')
    op.drop_table('orgs')
    op.drop_table('leads')
    # ### end Alembic commands ###
