"""no change check

Revision ID: 716822b92783
Revises: 61ba8c4b73f2
Create Date: 2026-02-22 15:21:33.239019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716822b92783'
down_revision = '61ba8c4b73f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_orgs_created_by_admin_id_users', 'users', ['created_by_admin_id'], ['id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orgs_created_by_admin_id_users', type_='foreignkey')

    # ### end Alembic commands ###
